security:
  user:
    password: password
spring:
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
logging:
  level:
    org.springframework.security: DEBUG