server:
  port: 9000
security:
  user:
    password: password
spring:
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost/mongodb
logging:
  level:
    org.springframework.security: DEBUG
